# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='dateDue',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='max_capacity',
            field=models.IntegerField(default=5),
        ),
    ]
