# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rats', '0002_auto_20170624_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_in_mins', models.IntegerField(default=90)),
            ],
        ),
    ]
