# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rats', '0003_auto_20170625_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='end_time',
            field=models.TimeField(default='11:00:00'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_time',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
