# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rats', '0004_auto_20170624_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residency',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residency',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
