# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rats', '0005_auto_20170624_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residency',
            name='duration_in_mins',
        ),
    ]
