# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rats', '0005_auto_20170706_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rats.Project'),
        ),
    ]
