# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rats', '0008_auto_20170624_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='residency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='rats.Residency'),
        ),
    ]
