# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rats', '0010_auto_20170624_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('residency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='rats.Residency')),
            ],
        ),
    ]
