# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rats', '0011_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='residency',
        ),
    ]
